# Directory & File Management
output_dir: null
overwrite_output_dir: true
logging_dir: null

# Training Control
do_train: true
do_eval: false
do_predict: false
num_train_epochs: 3.0
max_steps: -1

# Batch Configuration
per_device_train_batch_size: 2
gradient_accumulation_steps: 2
per_device_eval_batch_size: 2
eval_accumulation_steps: 2
dataloader_num_workers: 4

# Optimization
learning_rate: 1e-5
weight_decay: 0.0
warmup_ratio: 0.1
#warmup_steps: 0.01
gradient_checkpointing: false

# Evaluation
eval_strategy: "no"
eval_steps: null

# Logging & Saving
logging_strategy: "steps"
logging_steps: 1
save_strategy: "steps"
save_steps: 0.1
save_total_limit: null
save_only_model: true

# Precision & Performance
bf16: true
# Distributed Training
deepspeed: ds_z3_config.json
# Reporting
report_to: tensorboard